# Generated by Django 6.1 on 2026-09-15 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreraperiodo',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.ciclo'),
        ),
        migrations.AddField(
            model_name='carreraperiodo',
            name='paralelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_academica.paralelo'),
        ),
    ]
