# Generated by Django 6.1 on 2026-09-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0002_carreraperiodo_ciclo_carreraperiodo_paralelo'),
        ('usuarios', '0004_rename_ciclo_estudiante_semestre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ciclo',
            new_name='Semestre',
        ),
        migrations.RenameField(
            model_name='carreraperiodo',
            old_name='ciclo',
            new_name='semestre',
        ),
        migrations.RenameField(
            model_name='paralelo',
            old_name='ciclo',
            new_name='semestre',
        ),
        migrations.AddField(
            model_name='carrera',
            name='total_semestres',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
