# Generated by Django 6.1 on 2026-09-26 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0006_semestre_horas_practicas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ['-estado', '-fecha_inicio', '-id']},
        ),
    ]
