# Generated by Django 6.1 on 2026-09-21 16:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0002_initial'),
        ('empresas', '0002_empresa_latitud_empresa_longitud_and_more'),
        ('usuarios', '0010_estudiante_horas_acumuladas'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaTutorAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('ubicacion_entrada', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('ubicacion_salida', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('actividades', models.TextField(blank=True)),
                ('estado', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas_tutor_academico', to='empresas.empresa')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='usuarios.tutoracademico')),
            ],
            options={
                'ordering': ['-fecha', '-hora_entrada', '-id'],
            },
        ),
    ]
