# Generated by Django 6.1 on 2026-09-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='latitud',
            field=models.FloatField(blank=True, help_text='Latitud WGS84, ejemplo: -0.1807', null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='longitud',
            field=models.FloatField(blank=True, help_text='Longitud WGS84, ejemplo: -78.4834', null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='radio_permitido',
            field=models.FloatField(default=50.0),
        ),
    ]
