# Generated by Django 6.1 on 2026-09-15 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('usuarios', '0002_alter_estudiante_carrera_alter_estudiante_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoracademico',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
    ]
