# Generated by Django 6.1 on 2026-09-15 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_tutoracademico_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='ciclo',
            new_name='semestre',
        ),
    ]
